#!/usr/bin/env bash
# Start the agent-sentry API + static frontend, backgrounded. PIDs are written to
# .ui.pids so stop-ui.sh can tear them down. Re-running is refused while a pidfile exists.
#
# Config (env, with defaults):
#   API_PORT   (8787)  port for the FastAPI backend
#   UI_PORT    (8080)  port for the static frontend
#   API_HOST   (127.0.0.1)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

API_HOST="${API_HOST:-127.0.0.1}"
API_PORT="${API_PORT:-8787}"
UI_PORT="${UI_PORT:-8080}"
PIDFILE="$ROOT/.ui.pids"
LOGDIR="$ROOT/.ui-logs"
VENV="$ROOT/.venv/bin"

if [[ -f "$PIDFILE" ]]; then
  echo "Already running (found $PIDFILE). Run ./stop-ui.sh first." >&2
  exit 1
fi

if [[ ! -x "$VENV/uvicorn" || ! -x "$VENV/python" ]]; then
  echo "Missing .venv. Create it and install deps (e.g. 'uv sync' or 'pip install -e .')." >&2
  exit 1
fi

# Resolve SENTRY_API_KEY from the environment, falling back to .env. The value is kept in a
# shell variable only — never passed as a command-line argument (CLAUDE.md: no secrets in argv).
API_KEY="${SENTRY_API_KEY:-}"
if [[ -z "$API_KEY" && -f "$ROOT/.env" ]]; then
  # Take the last SENTRY_API_KEY= line; strip an optional surrounding pair of quotes.
  API_KEY="$(grep -E '^SENTRY_API_KEY=' "$ROOT/.env" | tail -n1 | cut -d= -f2-)"
  API_KEY="${API_KEY%\"}"; API_KEY="${API_KEY#\"}"
  API_KEY="${API_KEY%\'}"; API_KEY="${API_KEY#\'}"
fi

# The API refuses to serve without a key (503), so warn early with a clear message.
if [[ -z "$API_KEY" ]]; then
  echo "SENTRY_API_KEY is not set (env or .env). The API will return 503 until it is." >&2
fi

# Tell the API which origin to allow for CORS (must match the frontend URL).
export SENTRY_UI_ORIGIN="${SENTRY_UI_ORIGIN:-http://${API_HOST}:${UI_PORT}}"

# Generate frontend/config.js so the UI auto-connects using the .env-provided credentials and
# never prompts the user for them. The key is passed to python via the environment (not argv),
# and JSON-encoded for safe embedding. This file is gitignored — it must never be committed.
API_BASE="http://${API_HOST}:${API_PORT}"
SENTRY_CFG_BASE="$API_BASE" SENTRY_CFG_KEY="$API_KEY" "$VENV/python" - >"$ROOT/frontend/config.js" <<'PY'
import json, os
cfg = {"baseUrl": os.environ["SENTRY_CFG_BASE"], "apiKey": os.environ.get("SENTRY_CFG_KEY", "")}
print("// Generated by start-ui.sh from .env. DO NOT COMMIT (gitignored).")
print("window.SENTRY_CONFIG = " + json.dumps(cfg) + ";")
PY

mkdir -p "$LOGDIR"

echo "Starting API on http://${API_HOST}:${API_PORT} ..."
PYTHONPATH="$ROOT/src" "$VENV/uvicorn" sentry_api:app \
  --host "$API_HOST" --port "$API_PORT" --log-level info \
  >"$LOGDIR/api.log" 2>&1 &
API_PID=$!

echo "Starting frontend on http://${API_HOST}:${UI_PORT} ..."
"$VENV/python" -m http.server "$UI_PORT" --directory "$ROOT/frontend" --bind "$API_HOST" \
  >"$LOGDIR/ui.log" 2>&1 &
UI_PID=$!

printf '%s\n%s\n' "$API_PID" "$UI_PID" >"$PIDFILE"

# Give them a moment, then confirm both are still alive.
sleep 2
for pid in "$API_PID" "$UI_PID"; do
  if ! kill -0 "$pid" 2>/dev/null; then
    echo "A server failed to start. Check $LOGDIR/api.log and $LOGDIR/ui.log." >&2
    rm -f "$PIDFILE"
    kill "$API_PID" "$UI_PID" 2>/dev/null || true
    exit 1
  fi
done

echo "Up. Open http://${API_HOST}:${UI_PORT}  (API pid $API_PID, UI pid $UI_PID)"
echo "Logs: $LOGDIR/  |  Stop: ./stop-ui.sh"
